### ISSUE TITLE
Confusion regarding DiffSharp-cuda-windows bundle

### ISSUE THREAD

**Issue by VisualMelon** [DiffSharp/DiffSharp#169]
I can't get the DiffSharp-cuda-windows bundle to work. Three things that confuse me:
 1.  It depends on `libtorch-cuda-10.2-linux-x64` (rather than `libtorch-cuda-10.2-win-x64`), which naturally doesn't contain the necessary DLLs to run under windows
 2. Any attempt to restore it seems to fail, and I don't understand why; the DiffSharp-cpu bundle restores just fine, and looks mostly the same. The error is "Package 'DiffSharp-cuda-windows' is incompatible with 'all' frameworks in project". This doesn't seem to be transient or machine specific problem, but I don't understand it, so it might just be me.
 3. It targets netcoreapp3.0; I'd have expected it to be netstandard2.1 (per the nuspec); however, I see this was explicitly changed recently, so I assume there is a reason for this.

On a positive note, I have successfully got CUDA/GPU working under windows by manually adding the following dependencies (the newly added CI builds on nuget):
 - DiffSharp.Backends.Torch Version="1.0.0-preview-243323135"
 - DiffSharp.Core Version="1.0.0-preview-243323135"
 - libtorch-cuda-10.2-win-x64 Version="1.5.6"

Incidentally, I'm probably going to end up using DiffSharp for significantly more work in the near future, and I recall something about testing under Windows GPU being a problem: I'd be happy to put some effort in if it's something I can help with (my main machine is Win 10 with an RTX 2060 Super).

**Comment by dsyme** [comment]
Thanks should be fixed by https://github.com/DiffSharp/DiffSharp/pull/170

**Comment by VisualMelon** [comment]
Great, I'll report back once that gest to the CI and I find a minute to test it.

**Comment by dsyme** [comment]
> Incidentally, I'm probably going to end up using DiffSharp for significantly more work in the near future, and I recall something about testing under Windows GPU being a problem: I'd be happy to put some effort in if it's something I can help with (my main machine is Win 10 with an RTX 2060 Super).

We currently do manual testing on GPU from time to time on roughly this kind of machine.  Last time I checked we had a couple of tiny errors in test, see https://github.com/DiffSharp/DiffSharp/issues/147

Anything you can do to either automate or manually run tests (and fix them up, report on status etc.) would be very much appreciated!!

**Comment by dsyme** [comment]
@VisualMelon We'd also love any GPU testing on Linux you happen to be able to muster

**Comment by VisualMelon** [comment]
I'm afraid that didn't resolve the restoring problem. After much confusion, I have been able to get it to work locally by renaming the project to `DiffSharp.cuda.windows`. I can't find any documentation on why this should matter...

**Comment by dsyme** [comment]
> Edit: it restores but doesn't seem to pull down LibTorchSharp properly... I think it just can't pull dependencies from different sources (though I'm sure myget achieves this somehow; I don't know enough about nuget).

Could you send me a repro notebook, script or project?  I'll try it locally.  I just want to make sure everything is set up the same when I try

**Comment by VisualMelon** [comment]
It suffices to create a new project and try to pull it.

    dotnet new console -n DiffSharpCudaTest --lang f#
    cd DiffSharpCudaTest
    dotnet add package DiffSharp-cuda-windows --version 1.0.0-preview-243478925

I've tried on 3 machines, and I am completely befuddled.

**Comment by dsyme** [comment]
ok thanks

**Comment by dsyme** [comment]
Took another stab at this here, and actually tested it locally this time.  Will also re-test once the packages get to nuget.org

https://github.com/DiffSharp/DiffSharp/pull/171

**Comment by dsyme** [comment]
FWIW I just stopped using an explicit nuspec.  We'd done that to avoid forcing the download/restore of the CUDA packages when preparing the package.  

I can't spot the difference between the two techniques.  Strange. Anyway let's see

**Comment by VisualMelon** [comment]
I've been able to add and use https://www.nuget.org/packages/DiffSharp-cuda-windows/1.0.0-preview-244918410 in multiple projects, and was able to restore https://www.nuget.org/packages/DiffSharp-cuda-linux/1.0.0-preview-244918410 on a linux box also. Thanks for your prompt support.

**Comment by VisualMelon** [comment]
In other news, I ran all the tests with the GPU/Torch device, and they all passed.

**Comment by dsyme** [comment]
Yay!  And thank you for running the tests!

**Comment by dsyme** [comment]
(I assume that was on Windows?)

**Comment by VisualMelon** [comment]
Yeah, sorry, I'll edit that in ;)

I've not got GPU working on a linux box yet (not a priority), but I'll have another go at it soon, then it should be no problem to run the tests occasionally.

**Comment by kevmal** [comment]
All tests pass GPU/Torch linux

**Comment by dsyme** [comment]
Thank you for reporting that!
